version: "3.8"

services:
  mongodb-example:
    container_name: mongodb-example
    image: mongo:latest
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: khannedy
      MONGO_INITDB_ROOT_PASSWORD: khannedy
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "mongo-data1:/data/db"
  mongodb-express-example:
    container_name: mongodb-express-example
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongodb-example
    ports:
      - "8083:8081"
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 50M
        limits:
          cpus: "0.5"
          memory: 100M
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: khannedy
      ME_CONFIG_MONGODB_ADMINPASSWORD: khannedy
      ME_CONFIG_MONGODB_SERVER: mongodb-example
volumes:
  mongo-data1:
    name: mongo-data1
  mongo-data2:
    name: mongo-data2