version: "3.8"

services:
  mongodb-example:
    container_name: mongodb-example
    image: mongo:latest
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: khannedy
      MONGO_INITDB_ROOT_PASSWORD: khannedy
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "mongo-data1:/data/db"
volumes:
  mongo-data1:
    name: mongo-data1
  mongo-data2:
    name: mongo-data2